### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by cheddar-cheeze** [cheddar-cheeze/kisak-bot#1]
Suggest any features you'd like to be added, also id like your input too @kiask-valve

**Comment by cheddar-cheeze** [comment]
# todo
- [ ] mention spam detection/punishment
- [ ] opencv nsfw scan module
- [ ] more kisak memes
- [ ] more valve memes
- [ ] database inetergration
- [ ] xp system
- [ ] rep system
- [ ] warning system
- [ ] music streaming feature
- [ ] command logger
- [ ] audit logger
- [ ] chat spam detection/punishment
- [ ] raid detection/punishment
